# Generated by Django 5.0.7 on 2024-07-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDischargeDetails',
            new_name='PatientDischargeDetail',
        ),
    ]
